version: "3.8"
services:
  CLPainter:
    container_name: CLPainter
    image: harbor.techfin.ai/wjl-toolkit/cl_painter:2.0
    build:
      context: .
      dockerfile: "docker/Dockerfile"
      args:
        INSTALL_EXE: "Miniforge3-25.3.1-0-Linux-x86_64.sh"
        INSTALL_PATH: ${INSTALL_PATH}
        CONDA_ENV_NAME: ${CONDA_ENV_NAME}
        UPDATE_ENV_PYTHON_VERSION: "3.12"
        DUFS_URL: "172.17.1.5:5000"
        PRJ_DIR: ${PRJ_DIR}
        ROOT_DIR: ${ROOT_DIR}
        LOG_DIR: ${LOG_DIR}
    env_file:
      - .env
    ports:
      - "36602:22"
      - "15000:8001"
    volumes:
      - /DataDepartment:/DataDepartment:ro
    restart: always
    privileged: true
#    command: ["sh", "-c", "tail -f /dev/null"]
    command:  /root/CLPainter/web/backend/run.sh & && /usr/sbin/sshd -f /etc/ssh/sshd_config -D
#    ["/root/CLPainter/web/backend/run.sh"]
#    extra_hosts:

#      - "x86_64-conda-linux-gnu:127.0.0.1"
